INSERT INTO municipio (id,city_name) VALUES ('1','Abatiá');
INSERT INTO municipio (id,city_name) VALUES ('2','Agudos do Sul');
INSERT INTO municipio (id,city_name) VALUES ('3','Altamira do Paraná');
INSERT INTO municipio (id,city_name) VALUES ('4','Alto Piquiri');
INSERT INTO municipio (id,city_name) VALUES ('5','Alvorada do Sul');
INSERT INTO municipio (id,city_name) VALUES ('6','Ampére');
INSERT INTO municipio (id,city_name) VALUES ('7','Anahy');
INSERT INTO municipio (id,city_name) VALUES ('8','Andirá');
INSERT INTO municipio (id,city_name) VALUES ('9','Ângulo');
INSERT INTO municipio (id,city_name) VALUES ('10','Antônio Olinto');
INSERT INTO municipio (id,city_name) VALUES ('11','Apucarana');
INSERT INTO municipio (id,city_name) VALUES ('12','Arapongas');
INSERT INTO municipio (id,city_name) VALUES ('13','Arapoti');
INSERT INTO municipio (id,city_name) VALUES ('14','Arapuã');
INSERT INTO municipio (id,city_name) VALUES ('15','Araruna');
INSERT INTO municipio (id,city_name) VALUES ('16','Araucária');
INSERT INTO municipio (id,city_name) VALUES ('17','Ariranha do Ivaí');
INSERT INTO municipio (id,city_name) VALUES ('18','Assaí');
INSERT INTO municipio (id,city_name) VALUES ('19','Assis Chateaubriand');
INSERT INTO municipio (id,city_name) VALUES ('20','Astorga');
INSERT INTO municipio (id,city_name) VALUES ('21','Atalaia');
INSERT INTO municipio (id,city_name) VALUES ('22','Balsa Nova');
INSERT INTO municipio (id,city_name) VALUES ('23','Bandeirantes');
INSERT INTO municipio (id,city_name) VALUES ('24','Barbosa Ferraz');
INSERT INTO municipio (id,city_name) VALUES ('25','Barra do Jacaré');
INSERT INTO municipio (id,city_name) VALUES ('26','Barracão');
INSERT INTO municipio (id,city_name) VALUES ('27','Bela Vista da Caroba');
INSERT INTO municipio (id,city_name) VALUES ('28','Bela Vista do Paraíso');
INSERT INTO municipio (id,city_name) VALUES ('29','Bituruna');
INSERT INTO municipio (id,city_name) VALUES ('30','Boa Esperança');
INSERT INTO municipio (id,city_name) VALUES ('31','Boa Esperança do Iguaçu');
INSERT INTO municipio (id,city_name) VALUES ('32','Boa Ventura de São Roque');
INSERT INTO municipio (id,city_name) VALUES ('33','Boa Vista da Aparecida');
INSERT INTO municipio (id,city_name) VALUES ('34','Bom Jesus do Sul');
INSERT INTO municipio (id,city_name) VALUES ('35','Bom Sucesso');
INSERT INTO municipio (id,city_name) VALUES ('36','Bom Sucesso do Sul');
INSERT INTO municipio (id,city_name) VALUES ('37','Borrazópolis');
INSERT INTO municipio (id,city_name) VALUES ('38','Braganey');
INSERT INTO municipio (id,city_name) VALUES ('39','Brasilândia do Sul');
INSERT INTO municipio (id,city_name) VALUES ('40','Cafelândia');
INSERT INTO municipio (id,city_name) VALUES ('41','Califórnia');
INSERT INTO municipio (id,city_name) VALUES ('42','Cambará');
INSERT INTO municipio (id,city_name) VALUES ('43','Cambé');
INSERT INTO municipio (id,city_name) VALUES ('44','Cambira');
INSERT INTO municipio (id,city_name) VALUES ('45','Campina da Lagoa');
INSERT INTO municipio (id,city_name) VALUES ('46','Campina do Simão');
INSERT INTO municipio (id,city_name) VALUES ('47','Campo Bonito');
INSERT INTO municipio (id,city_name) VALUES ('48','Campo do Tenente');
INSERT INTO municipio (id,city_name) VALUES ('49','Campo Largo');
INSERT INTO municipio (id,city_name) VALUES ('50','Campo Magro');
INSERT INTO municipio (id,city_name) VALUES ('51','Campo Mourão');
INSERT INTO municipio (id,city_name) VALUES ('52','Cândido de Abreu');
INSERT INTO municipio (id,city_name) VALUES ('53','Candói');
INSERT INTO municipio (id,city_name) VALUES ('54','Cantagalo');
INSERT INTO municipio (id,city_name) VALUES ('55','Capanema');
INSERT INTO municipio (id,city_name) VALUES ('56','Capitão Leônidas Marques');
INSERT INTO municipio (id,city_name) VALUES ('57','Carambeí');
INSERT INTO municipio (id,city_name) VALUES ('58','Carlópolis');
INSERT INTO municipio (id,city_name) VALUES ('59','Cascavel');
INSERT INTO municipio (id,city_name) VALUES ('60','Castro');
INSERT INTO municipio (id,city_name) VALUES ('61','Catanduvas');
INSERT INTO municipio (id,city_name) VALUES ('62','Céu Azul');
INSERT INTO municipio (id,city_name) VALUES ('63','Chopinzinho');
INSERT INTO municipio (id,city_name) VALUES ('64','Cianorte');
INSERT INTO municipio (id,city_name) VALUES ('65','Clevelândia');
INSERT INTO municipio (id,city_name) VALUES ('66','Congonhinhas');
INSERT INTO municipio (id,city_name) VALUES ('67','Conselheiro Mairinck');
INSERT INTO municipio (id,city_name) VALUES ('68','Contenda');
INSERT INTO municipio (id,city_name) VALUES ('69','Corbélia');
INSERT INTO municipio (id,city_name) VALUES ('70','Cornélio Procópio');
INSERT INTO municipio (id,city_name) VALUES ('71','Coronel Domingos Soares');
INSERT INTO municipio (id,city_name) VALUES ('72','Coronel Vivida');
INSERT INTO municipio (id,city_name) VALUES ('73','Corumbataí do Sul');
INSERT INTO municipio (id,city_name) VALUES ('74','Cruz Machado');
INSERT INTO municipio (id,city_name) VALUES ('75','Cruzeiro do Iguaçu');
INSERT INTO municipio (id,city_name) VALUES ('76','Cruzeiro do Oeste');
INSERT INTO municipio (id,city_name) VALUES ('77','Cruzmaltina');
INSERT INTO municipio (id,city_name) VALUES ('78','Curiúva');
INSERT INTO municipio (id,city_name) VALUES ('79','Diamante do Sul');
INSERT INTO municipio (id,city_name) VALUES ('80','Diamante D\'Oeste');
INSERT INTO municipio (id,city_name) VALUES ('81','Dois Vizinhos');
INSERT INTO municipio (id,city_name) VALUES ('82','Doutor Camargo');
INSERT INTO municipio (id,city_name) VALUES ('83','Enéas Marques');
INSERT INTO municipio (id,city_name) VALUES ('84','Engenheiro Beltrão');
INSERT INTO municipio (id,city_name) VALUES ('85','Entre Rios do Oeste');
INSERT INTO municipio (id,city_name) VALUES ('86','Espigão Alto do Iguaçu');
INSERT INTO municipio (id,city_name) VALUES ('87','Farol');
INSERT INTO municipio (id,city_name) VALUES ('88','Faxinal');
INSERT INTO municipio (id,city_name) VALUES ('89','Fazenda Rio Grande');
INSERT INTO municipio (id,city_name) VALUES ('90','Fênix');
INSERT INTO municipio (id,city_name) VALUES ('91','Fernandes Pinheiro');
INSERT INTO municipio (id,city_name) VALUES ('92','Figueira');
INSERT INTO municipio (id,city_name) VALUES ('93','Flor da Serra do Sul');
INSERT INTO municipio (id,city_name) VALUES ('94','Floraí');
INSERT INTO municipio (id,city_name) VALUES ('95','Floresta');
INSERT INTO municipio (id,city_name) VALUES ('96','Florestópolis');
INSERT INTO municipio (id,city_name) VALUES ('97','Formosa do Oeste');
INSERT INTO municipio (id,city_name) VALUES ('98','Foz do Iguaçu');
INSERT INTO municipio (id,city_name) VALUES ('99','Foz do Jordão');
INSERT INTO municipio (id,city_name) VALUES ('100','Francisco Alves');
INSERT INTO municipio (id,city_name) VALUES ('101','Francisco Beltrão');
INSERT INTO municipio (id,city_name) VALUES ('102','Godoy Moreira');
INSERT INTO municipio (id,city_name) VALUES ('103','Goioerê');
INSERT INTO municipio (id,city_name) VALUES ('104','Goioxim');
INSERT INTO municipio (id,city_name) VALUES ('105','Grandes Rios');
INSERT INTO municipio (id,city_name) VALUES ('106','Guaíra');
INSERT INTO municipio (id,city_name) VALUES ('107','Guamiranga');
INSERT INTO municipio (id,city_name) VALUES ('108','Guapirama');
INSERT INTO municipio (id,city_name) VALUES ('109','Guaraniaçu');
INSERT INTO municipio (id,city_name) VALUES ('110','Guarapuava');
INSERT INTO municipio (id,city_name) VALUES ('111','Honório Serpa');
INSERT INTO municipio (id,city_name) VALUES ('112','Ibaiti');
INSERT INTO municipio (id,city_name) VALUES ('113','Ibema');
INSERT INTO municipio (id,city_name) VALUES ('114','Ibiporã');
INSERT INTO municipio (id,city_name) VALUES ('115','Iguaraçu');
INSERT INTO municipio (id,city_name) VALUES ('116','Iguatu');
INSERT INTO municipio (id,city_name) VALUES ('117','Imbaú');
INSERT INTO municipio (id,city_name) VALUES ('118','Imbituva');
INSERT INTO municipio (id,city_name) VALUES ('119','Inácio Martins');
INSERT INTO municipio (id,city_name) VALUES ('120','Ipiranga');
INSERT INTO municipio (id,city_name) VALUES ('121','Iporã');
INSERT INTO municipio (id,city_name) VALUES ('122','Iracema do Oeste');
INSERT INTO municipio (id,city_name) VALUES ('123','Irati');
INSERT INTO municipio (id,city_name) VALUES ('124','Iretama');
INSERT INTO municipio (id,city_name) VALUES ('125','Itaipulândia');
INSERT INTO municipio (id,city_name) VALUES ('126','Itambaracá');
INSERT INTO municipio (id,city_name) VALUES ('127','Itambé');
INSERT INTO municipio (id,city_name) VALUES ('128','Itapejara d\'Oeste');
INSERT INTO municipio (id,city_name) VALUES ('129','Ivaí');
INSERT INTO municipio (id,city_name) VALUES ('130','Ivaiporã');
INSERT INTO municipio (id,city_name) VALUES ('131','Ivatuba');
INSERT INTO municipio (id,city_name) VALUES ('132','Jaboti');
INSERT INTO municipio (id,city_name) VALUES ('133','Jacarezinho');
INSERT INTO municipio (id,city_name) VALUES ('134','Jaguapitã');
INSERT INTO municipio (id,city_name) VALUES ('135','Jaguariaíva');
INSERT INTO municipio (id,city_name) VALUES ('136','Jandaia do Sul');
INSERT INTO municipio (id,city_name) VALUES ('137','Janiópolis');
INSERT INTO municipio (id,city_name) VALUES ('138','Japira');
INSERT INTO municipio (id,city_name) VALUES ('139','Jardim Alegre');
INSERT INTO municipio (id,city_name) VALUES ('140','Jataizinho');
INSERT INTO municipio (id,city_name) VALUES ('141','Jesuítas');
INSERT INTO municipio (id,city_name) VALUES ('142','Joaquim Távora');
INSERT INTO municipio (id,city_name) VALUES ('143','Jundiaí do Sul');
INSERT INTO municipio (id,city_name) VALUES ('144','Juranda');
INSERT INTO municipio (id,city_name) VALUES ('145','Jussara');
INSERT INTO municipio (id,city_name) VALUES ('146','Kaloré');
INSERT INTO municipio (id,city_name) VALUES ('147','Lapa');
INSERT INTO municipio (id,city_name) VALUES ('148','Laranjal');
INSERT INTO municipio (id,city_name) VALUES ('149','Laranjeiras do Sul');
INSERT INTO municipio (id,city_name) VALUES ('150','Leópolis');
INSERT INTO municipio (id,city_name) VALUES ('151','Lidianópolis');
INSERT INTO municipio (id,city_name) VALUES ('152','Lindoeste');
INSERT INTO municipio (id,city_name) VALUES ('153','Londrina');
INSERT INTO municipio (id,city_name) VALUES ('154','Luiziana');
INSERT INTO municipio (id,city_name) VALUES ('155','Lunardelli');
INSERT INTO municipio (id,city_name) VALUES ('156','Lupionópolis');
INSERT INTO municipio (id,city_name) VALUES ('157','Mallet');
INSERT INTO municipio (id,city_name) VALUES ('158','Mamborê');
INSERT INTO municipio (id,city_name) VALUES ('159','Mandaguaçu');
INSERT INTO municipio (id,city_name) VALUES ('160','Mandaguari');
INSERT INTO municipio (id,city_name) VALUES ('161','Manfrinópolis');
INSERT INTO municipio (id,city_name) VALUES ('162','Mangueirinha');
INSERT INTO municipio (id,city_name) VALUES ('163','Manoel Ribas');
INSERT INTO municipio (id,city_name) VALUES ('164','Marechal Cândido Rondon');
INSERT INTO municipio (id,city_name) VALUES ('165','Marialva');
INSERT INTO municipio (id,city_name) VALUES ('166','Marilândia do Sul');
INSERT INTO municipio (id,city_name) VALUES ('167','Mariluz');
INSERT INTO municipio (id,city_name) VALUES ('168','Maringá');
INSERT INTO municipio (id,city_name) VALUES ('169','Mariópolis');
INSERT INTO municipio (id,city_name) VALUES ('170','Maripá');
INSERT INTO municipio (id,city_name) VALUES ('171','Marmeleiro');
INSERT INTO municipio (id,city_name) VALUES ('172','Marquinho');
INSERT INTO municipio (id,city_name) VALUES ('173','Marumbi');
INSERT INTO municipio (id,city_name) VALUES ('174','Matelândia');
INSERT INTO municipio (id,city_name) VALUES ('175','Mato Rico');
INSERT INTO municipio (id,city_name) VALUES ('176','Mauá da Serra');
INSERT INTO municipio (id,city_name) VALUES ('177','Medianeira');
INSERT INTO municipio (id,city_name) VALUES ('178','Mercedes');
INSERT INTO municipio (id,city_name) VALUES ('179','Missal');
INSERT INTO municipio (id,city_name) VALUES ('180','Moreira Sales');
INSERT INTO municipio (id,city_name) VALUES ('181','Munhoz de Melo');
INSERT INTO municipio (id,city_name) VALUES ('182','Nova América da Colina');
INSERT INTO municipio (id,city_name) VALUES ('183','Nova Aurora');
INSERT INTO municipio (id,city_name) VALUES ('184','Nova Cantu');
INSERT INTO municipio (id,city_name) VALUES ('185','Nova Esperança');
INSERT INTO municipio (id,city_name) VALUES ('186','Nova Esperança do Sudoeste');
INSERT INTO municipio (id,city_name) VALUES ('187','Nova Fátima');
INSERT INTO municipio (id,city_name) VALUES ('188','Nova Laranjeiras');
INSERT INTO municipio (id,city_name) VALUES ('189','Nova Prata do Iguaçu');
INSERT INTO municipio (id,city_name) VALUES ('190','Nova Santa Bárbara');
INSERT INTO municipio (id,city_name) VALUES ('191','Nova Santa Rosa');
INSERT INTO municipio (id,city_name) VALUES ('192','Nova Tebas');
INSERT INTO municipio (id,city_name) VALUES ('193','Novo Itacolomi');
INSERT INTO municipio (id,city_name) VALUES ('194','Ortigueira');
INSERT INTO municipio (id,city_name) VALUES ('195','Ourizona');
INSERT INTO municipio (id,city_name) VALUES ('196','Ouro Verde do Oeste');
INSERT INTO municipio (id,city_name) VALUES ('197','Paiçandu');
INSERT INTO municipio (id,city_name) VALUES ('198','Palmas');
INSERT INTO municipio (id,city_name) VALUES ('199','Palmeira');
INSERT INTO municipio (id,city_name) VALUES ('200','Palmital');
INSERT INTO municipio (id,city_name) VALUES ('201','Palotina');
INSERT INTO municipio (id,city_name) VALUES ('202','Pato Bragado');
INSERT INTO municipio (id,city_name) VALUES ('203','Pato Branco');
INSERT INTO municipio (id,city_name) VALUES ('204','Paula Freitas');
INSERT INTO municipio (id,city_name) VALUES ('205','Paulo Frontin');
INSERT INTO municipio (id,city_name) VALUES ('206','Peabiru');
INSERT INTO municipio (id,city_name) VALUES ('207','Perobal');
INSERT INTO municipio (id,city_name) VALUES ('208','Pérola d\'Oeste');
INSERT INTO municipio (id,city_name) VALUES ('209','Piên');
INSERT INTO municipio (id,city_name) VALUES ('210','Pinhal de São Bento');
INSERT INTO municipio (id,city_name) VALUES ('211','Pinhalão');
INSERT INTO municipio (id,city_name) VALUES ('212','Pinhão');
INSERT INTO municipio (id,city_name) VALUES ('213','Piraí do Sul');
INSERT INTO municipio (id,city_name) VALUES ('214','Pitanga');
INSERT INTO municipio (id,city_name) VALUES ('215','Pitangueiras');
INSERT INTO municipio (id,city_name) VALUES ('216','Planalto');
INSERT INTO municipio (id,city_name) VALUES ('217','Ponta Grossa');
INSERT INTO municipio (id,city_name) VALUES ('218','Porto Amazonas');
INSERT INTO municipio (id,city_name) VALUES ('219','Porto Barreiro');
INSERT INTO municipio (id,city_name) VALUES ('220','Porto Vitória');
INSERT INTO municipio (id,city_name) VALUES ('221','Prado Ferreira');
INSERT INTO municipio (id,city_name) VALUES ('222','Pranchita');
INSERT INTO municipio (id,city_name) VALUES ('223','Primeiro de Maio');
INSERT INTO municipio (id,city_name) VALUES ('224','Prudentópolis');
INSERT INTO municipio (id,city_name) VALUES ('225','Quarto Centenário');
INSERT INTO municipio (id,city_name) VALUES ('226','Quatro Pontes');
INSERT INTO municipio (id,city_name) VALUES ('227','Quedas do Iguaçu');
INSERT INTO municipio (id,city_name) VALUES ('228','Quinta do Sol');
INSERT INTO municipio (id,city_name) VALUES ('229','Quitandinha');
INSERT INTO municipio (id,city_name) VALUES ('230','Ramilândia');
INSERT INTO municipio (id,city_name) VALUES ('231','Rancho Alegre');
INSERT INTO municipio (id,city_name) VALUES ('232','Rancho Alegre D\'Oeste');
INSERT INTO municipio (id,city_name) VALUES ('233','Realeza');
INSERT INTO municipio (id,city_name) VALUES ('234','Rebouças');
INSERT INTO municipio (id,city_name) VALUES ('235','Renascença');
INSERT INTO municipio (id,city_name) VALUES ('236','Reserva');
INSERT INTO municipio (id,city_name) VALUES ('237','Reserva do Iguaçu');
INSERT INTO municipio (id,city_name) VALUES ('238','Ribeirão Claro');
INSERT INTO municipio (id,city_name) VALUES ('239','Ribeirão do Pinhal');
INSERT INTO municipio (id,city_name) VALUES ('240','Rio Azul');
INSERT INTO municipio (id,city_name) VALUES ('241','Rio Bom');
INSERT INTO municipio (id,city_name) VALUES ('242','Rio Bonito do Iguaçu');
INSERT INTO municipio (id,city_name) VALUES ('243','Rio Branco do Ivaí');
INSERT INTO municipio (id,city_name) VALUES ('244','Rio Negro');
INSERT INTO municipio (id,city_name) VALUES ('245','Rolândia');
INSERT INTO municipio (id,city_name) VALUES ('246','Roncador');
INSERT INTO municipio (id,city_name) VALUES ('247','Rosário do Ivaí');
INSERT INTO municipio (id,city_name) VALUES ('248','Sabáudia');
INSERT INTO municipio (id,city_name) VALUES ('249','Salgado Filho');
INSERT INTO municipio (id,city_name) VALUES ('250','Salto do Itararé');
INSERT INTO municipio (id,city_name) VALUES ('251','Salto do Lontra');
INSERT INTO municipio (id,city_name) VALUES ('252','Santa Amélia');
INSERT INTO municipio (id,city_name) VALUES ('253','Santa Cecília do Pavão');
INSERT INTO municipio (id,city_name) VALUES ('254','Santa Fé');
INSERT INTO municipio (id,city_name) VALUES ('255','Santa Helena');
INSERT INTO municipio (id,city_name) VALUES ('256','Santa Izabel do Oeste');
INSERT INTO municipio (id,city_name) VALUES ('257','Santa Lúcia');
INSERT INTO municipio (id,city_name) VALUES ('258','Santa Maria do Oeste');
INSERT INTO municipio (id,city_name) VALUES ('259','Santa Mariana');
INSERT INTO municipio (id,city_name) VALUES ('260','Santa Tereza do Oeste');
INSERT INTO municipio (id,city_name) VALUES ('261','Santa Terezinha de Itaipu');
INSERT INTO municipio (id,city_name) VALUES ('262','Santana do Itararé');
INSERT INTO municipio (id,city_name) VALUES ('263','Santo Antônio da Platina');
INSERT INTO municipio (id,city_name) VALUES ('264','Santo Antônio do Paraíso');
INSERT INTO municipio (id,city_name) VALUES ('265','Santo Antônio do Sudoeste');
INSERT INTO municipio (id,city_name) VALUES ('266','Santo Inácio');
INSERT INTO municipio (id,city_name) VALUES ('267','São Jerônimo da Serra');
INSERT INTO municipio (id,city_name) VALUES ('268','São João');
INSERT INTO municipio (id,city_name) VALUES ('269','São João do Ivaí');
INSERT INTO municipio (id,city_name) VALUES ('270','São João do Triunfo');
INSERT INTO municipio (id,city_name) VALUES ('271','São Jorge do Ivaí');
INSERT INTO municipio (id,city_name) VALUES ('272','São Jorge d\'Oeste');
INSERT INTO municipio (id,city_name) VALUES ('273','São José da Boa Vista');
INSERT INTO municipio (id,city_name) VALUES ('274','São José das Palmeiras');
INSERT INTO municipio (id,city_name) VALUES ('275','São José dos Pinhais');
INSERT INTO municipio (id,city_name) VALUES ('276','São Mateus do Sul');
INSERT INTO municipio (id,city_name) VALUES ('277','São Miguel do Iguaçu');
INSERT INTO municipio (id,city_name) VALUES ('278','São Pedro do Iguaçu');
INSERT INTO municipio (id,city_name) VALUES ('279','São Pedro do Ivaí');
INSERT INTO municipio (id,city_name) VALUES ('280','São Sebastião da Amoreira');
INSERT INTO municipio (id,city_name) VALUES ('281','São Tomé');
INSERT INTO municipio (id,city_name) VALUES ('282','Sapopema');
INSERT INTO municipio (id,city_name) VALUES ('283','Sarandi');
INSERT INTO municipio (id,city_name) VALUES ('284','Saudade do Iguaçu');
INSERT INTO municipio (id,city_name) VALUES ('285','Sengés');
INSERT INTO municipio (id,city_name) VALUES ('286','Serranópolis do Iguaçu');
INSERT INTO municipio (id,city_name) VALUES ('287','Sertaneja');
INSERT INTO municipio (id,city_name) VALUES ('288','Sertanópolis');
INSERT INTO municipio (id,city_name) VALUES ('289','Siqueira Campos');
INSERT INTO municipio (id,city_name) VALUES ('290','Sulina');
INSERT INTO municipio (id,city_name) VALUES ('291','Tamarana');
INSERT INTO municipio (id,city_name) VALUES ('292','Teixeira Soares');
INSERT INTO municipio (id,city_name) VALUES ('293','Terra Boa');
INSERT INTO municipio (id,city_name) VALUES ('294','Terra Roxa');
INSERT INTO municipio (id,city_name) VALUES ('295','Tibagi');
INSERT INTO municipio (id,city_name) VALUES ('296','Tijucas do Sul');
INSERT INTO municipio (id,city_name) VALUES ('297','Toledo');
INSERT INTO municipio (id,city_name) VALUES ('298','Tomazina');
INSERT INTO municipio (id,city_name) VALUES ('299','Três Barras do Paraná');
INSERT INTO municipio (id,city_name) VALUES ('300','Tuneiras do Oeste');
INSERT INTO municipio (id,city_name) VALUES ('301','Tupãssi');
INSERT INTO municipio (id,city_name) VALUES ('302','Turvo');
INSERT INTO municipio (id,city_name) VALUES ('303','Ubiratã');
INSERT INTO municipio (id,city_name) VALUES ('304','União da Vitória');
INSERT INTO municipio (id,city_name) VALUES ('305','Uraí');
INSERT INTO municipio (id,city_name) VALUES ('306','Ventania');
INSERT INTO municipio (id,city_name) VALUES ('307','Vera Cruz do Oeste');
INSERT INTO municipio (id,city_name) VALUES ('308','Verê');
INSERT INTO municipio (id,city_name) VALUES ('309','Virmond');
INSERT INTO municipio (id,city_name) VALUES ('310','Vitorino');
INSERT INTO municipio (id,city_name) VALUES ('311','Wenceslau Braz');

