# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 15:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cotador', '0002_auto_20170519_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='Culture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('culture_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Safra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('safra_inf', models.CharField(max_length=50)),
                ('safra_begin', models.DateTimeField(blank=True, null=True)),
                ('safra_end', models.DateTimeField(blank=True, null=True)),
                ('culture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotador.Culture')),
            ],
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nc_60', models.FloatField()),
                ('nc_65', models.FloatField()),
                ('nc_70', models.FloatField()),
                ('active', models.BooleanField(default=False)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotador.City')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotador.Product')),
                ('safra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotador.Safra')),
            ],
        ),
        migrations.CreateModel(
            name='Uf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=2)),
                ('uf_name', models.CharField(max_length=50)),
            ],
        ),
    ]
