# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 15:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cotador', '0003_culture_product_safra_tax_uf'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='uf',
            field=models.ForeignKey(default=16, on_delete=django.db.models.deletion.CASCADE, to='cotador.Uf'),
        ),
    ]
