# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 15:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cotador', '0004_city_uf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='city_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='uf',
            old_name='uf_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='city',
            name='uf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotador.Uf'),
        ),
    ]
