# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 15:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cotador', '0007_prod_esp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prod_esp',
            old_name='prod_esp',
            new_name='value',
        ),
        migrations.AddField(
            model_name='prod_esp',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cotador.Product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='safra',
            field=models.ForeignKey(default=-2004, on_delete=django.db.models.deletion.CASCADE, to='cotador.Safra'),
            preserve_default=False,
        ),
    ]
