# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotador', '0008_auto_20170523_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='safra',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
