# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 23:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cotador', '0011_lvl_cob'),
    ]

    operations = [
        migrations.AddField(
            model_name='culture',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cotador.Product'),
            preserve_default=False,
        ),
    ]
