# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 15:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cotador', '0014_auto_20170923_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='lvl_cob',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotador.Lvl_Cob'),
        ),
    ]
