# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 15:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cotador', '0016_auto_20170926_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='lvl_cob',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotador.Lvl_Cob'),
        ),
    ]
