# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 15:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cotador', '0017_auto_20170926_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='decision',
        ),
        migrations.RemoveField(
            model_name='status',
            name='choices',
        ),
        migrations.RemoveField(
            model_name='status',
            name='decision',
        ),
        migrations.AlterField(
            model_name='quotation',
            name='lvl_cob',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotador.Lvl_Cob'),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Decision',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
